onlyBuiltDependencies:
  - ' '
  - '-'
  - /
  - '3'
  - '@'
  - a
  - b
  - c
  - d
  - e
  - esbuild
  - f
  - h
  - i
  - j
  - k
  - l
  - msw
  - n
  - o
  - p
  - protobufjs
  - q
  - r
  - s
  - t
  - u
  - v
  - w
  - y
